# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.sso import auth_pb2 as proto_dot_sso_dot_auth__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/sso/auth_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AuthServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateToken = channel.unary_unary(
                '/sso.AuthService/ValidateToken',
                request_serializer=proto_dot_sso_dot_auth__pb2.ValidateTokenRequest.SerializeToString,
                response_deserializer=proto_dot_sso_dot_auth__pb2.ValidateTokenResponse.FromString,
                _registered_method=True)
        self.LoginWithEmail = channel.unary_unary(
                '/sso.AuthService/LoginWithEmail',
                request_serializer=proto_dot_sso_dot_auth__pb2.EmailLoginRequest.SerializeToString,
                response_deserializer=proto_dot_sso_dot_auth__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.LoginWithFirebase = channel.unary_unary(
                '/sso.AuthService/LoginWithFirebase',
                request_serializer=proto_dot_sso_dot_auth__pb2.FirebaseLoginRequest.SerializeToString,
                response_deserializer=proto_dot_sso_dot_auth__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.RefreshToken = channel.unary_unary(
                '/sso.AuthService/RefreshToken',
                request_serializer=proto_dot_sso_dot_auth__pb2.RefreshTokenRequest.SerializeToString,
                response_deserializer=proto_dot_sso_dot_auth__pb2.RefreshResponse.FromString,
                _registered_method=True)
        self.ExchangeSSOToken = channel.unary_unary(
                '/sso.AuthService/ExchangeSSOToken',
                request_serializer=proto_dot_sso_dot_auth__pb2.SSOExchangeRequest.SerializeToString,
                response_deserializer=proto_dot_sso_dot_auth__pb2.LoginResponse.FromString,
                _registered_method=True)
        self.Logout = channel.unary_unary(
                '/sso.AuthService/Logout',
                request_serializer=proto_dot_sso_dot_auth__pb2.LogoutRequest.SerializeToString,
                response_deserializer=proto_dot_sso_dot_auth__pb2.LogoutResponse.FromString,
                _registered_method=True)
        self.GetSessions = channel.unary_unary(
                '/sso.AuthService/GetSessions',
                request_serializer=proto_dot_sso_dot_auth__pb2.GetSessionsRequest.SerializeToString,
                response_deserializer=proto_dot_sso_dot_auth__pb2.GetSessionsResponse.FromString,
                _registered_method=True)


class AuthServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ValidateToken(self, request, context):
        """Validate JWT token dan return user data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginWithEmail(self, request, context):
        """Login dengan email dan password
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LoginWithFirebase(self, request, context):
        """Login dengan Firebase token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RefreshToken(self, request, context):
        """Refresh access token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExchangeSSOToken(self, request, context):
        """Exchange SSO token untuk app-specific tokens
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Logout(self, request, context):
        """Logout (global atau client-specific)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessions(self, request, context):
        """Get sessions untuk user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AuthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateToken,
                    request_deserializer=proto_dot_sso_dot_auth__pb2.ValidateTokenRequest.FromString,
                    response_serializer=proto_dot_sso_dot_auth__pb2.ValidateTokenResponse.SerializeToString,
            ),
            'LoginWithEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginWithEmail,
                    request_deserializer=proto_dot_sso_dot_auth__pb2.EmailLoginRequest.FromString,
                    response_serializer=proto_dot_sso_dot_auth__pb2.LoginResponse.SerializeToString,
            ),
            'LoginWithFirebase': grpc.unary_unary_rpc_method_handler(
                    servicer.LoginWithFirebase,
                    request_deserializer=proto_dot_sso_dot_auth__pb2.FirebaseLoginRequest.FromString,
                    response_serializer=proto_dot_sso_dot_auth__pb2.LoginResponse.SerializeToString,
            ),
            'RefreshToken': grpc.unary_unary_rpc_method_handler(
                    servicer.RefreshToken,
                    request_deserializer=proto_dot_sso_dot_auth__pb2.RefreshTokenRequest.FromString,
                    response_serializer=proto_dot_sso_dot_auth__pb2.RefreshResponse.SerializeToString,
            ),
            'ExchangeSSOToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ExchangeSSOToken,
                    request_deserializer=proto_dot_sso_dot_auth__pb2.SSOExchangeRequest.FromString,
                    response_serializer=proto_dot_sso_dot_auth__pb2.LoginResponse.SerializeToString,
            ),
            'Logout': grpc.unary_unary_rpc_method_handler(
                    servicer.Logout,
                    request_deserializer=proto_dot_sso_dot_auth__pb2.LogoutRequest.FromString,
                    response_serializer=proto_dot_sso_dot_auth__pb2.LogoutResponse.SerializeToString,
            ),
            'GetSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessions,
                    request_deserializer=proto_dot_sso_dot_auth__pb2.GetSessionsRequest.FromString,
                    response_serializer=proto_dot_sso_dot_auth__pb2.GetSessionsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sso.AuthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sso.AuthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AuthService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ValidateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sso.AuthService/ValidateToken',
            proto_dot_sso_dot_auth__pb2.ValidateTokenRequest.SerializeToString,
            proto_dot_sso_dot_auth__pb2.ValidateTokenResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoginWithEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sso.AuthService/LoginWithEmail',
            proto_dot_sso_dot_auth__pb2.EmailLoginRequest.SerializeToString,
            proto_dot_sso_dot_auth__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def LoginWithFirebase(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sso.AuthService/LoginWithFirebase',
            proto_dot_sso_dot_auth__pb2.FirebaseLoginRequest.SerializeToString,
            proto_dot_sso_dot_auth__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RefreshToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sso.AuthService/RefreshToken',
            proto_dot_sso_dot_auth__pb2.RefreshTokenRequest.SerializeToString,
            proto_dot_sso_dot_auth__pb2.RefreshResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExchangeSSOToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sso.AuthService/ExchangeSSOToken',
            proto_dot_sso_dot_auth__pb2.SSOExchangeRequest.SerializeToString,
            proto_dot_sso_dot_auth__pb2.LoginResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Logout(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sso.AuthService/Logout',
            proto_dot_sso_dot_auth__pb2.LogoutRequest.SerializeToString,
            proto_dot_sso_dot_auth__pb2.LogoutResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sso.AuthService/GetSessions',
            proto_dot_sso_dot_auth__pb2.GetSessionsRequest.SerializeToString,
            proto_dot_sso_dot_auth__pb2.GetSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
