# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.sso import user_pb2 as proto_dot_sso_dot_user__pb2

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in proto/sso/user_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UserServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUser = channel.unary_unary(
                '/sso.UserService/GetUser',
                request_serializer=proto_dot_sso_dot_user__pb2.GetUserRequest.SerializeToString,
                response_deserializer=proto_dot_sso_dot_user__pb2.UserResponse.FromString,
                _registered_method=True)
        self.GetUserByEmail = channel.unary_unary(
                '/sso.UserService/GetUserByEmail',
                request_serializer=proto_dot_sso_dot_user__pb2.GetUserByEmailRequest.SerializeToString,
                response_deserializer=proto_dot_sso_dot_user__pb2.UserResponse.FromString,
                _registered_method=True)
        self.GetUserByPhone = channel.unary_unary(
                '/sso.UserService/GetUserByPhone',
                request_serializer=proto_dot_sso_dot_user__pb2.GetUserByPhoneRequest.SerializeToString,
                response_deserializer=proto_dot_sso_dot_user__pb2.UserResponse.FromString,
                _registered_method=True)
        self.BatchGetUsers = channel.unary_unary(
                '/sso.UserService/BatchGetUsers',
                request_serializer=proto_dot_sso_dot_user__pb2.BatchGetUsersRequest.SerializeToString,
                response_deserializer=proto_dot_sso_dot_user__pb2.BatchGetUsersResponse.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/sso.UserService/CreateUser',
                request_serializer=proto_dot_sso_dot_user__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=proto_dot_sso_dot_user__pb2.CreateUserResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/sso.UserService/UpdateUser',
                request_serializer=proto_dot_sso_dot_user__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=proto_dot_sso_dot_user__pb2.UpdateUserResponse.FromString,
                _registered_method=True)
        self.RemoveUserFromApps = channel.unary_unary(
                '/sso.UserService/RemoveUserFromApps',
                request_serializer=proto_dot_sso_dot_user__pb2.RemoveUserFromAppsRequest.SerializeToString,
                response_deserializer=proto_dot_sso_dot_user__pb2.RemoveUserFromAppsResponse.FromString,
                _registered_method=True)
        self.AssignUserToApps = channel.unary_unary(
                '/sso.UserService/AssignUserToApps',
                request_serializer=proto_dot_sso_dot_user__pb2.AssignUserToAppsRequest.SerializeToString,
                response_deserializer=proto_dot_sso_dot_user__pb2.AssignUserToAppsResponse.FromString,
                _registered_method=True)


class UserServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUser(self, request, context):
        """Read operations
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByEmail(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserByPhone(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchGetUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Write operations (for HRIS integration)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveUserFromApps(self, request, context):
        """App assignment operations (delete is now app-specific, not user-delete)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AssignUserToApps(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UserServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=proto_dot_sso_dot_user__pb2.GetUserRequest.FromString,
                    response_serializer=proto_dot_sso_dot_user__pb2.UserResponse.SerializeToString,
            ),
            'GetUserByEmail': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByEmail,
                    request_deserializer=proto_dot_sso_dot_user__pb2.GetUserByEmailRequest.FromString,
                    response_serializer=proto_dot_sso_dot_user__pb2.UserResponse.SerializeToString,
            ),
            'GetUserByPhone': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserByPhone,
                    request_deserializer=proto_dot_sso_dot_user__pb2.GetUserByPhoneRequest.FromString,
                    response_serializer=proto_dot_sso_dot_user__pb2.UserResponse.SerializeToString,
            ),
            'BatchGetUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchGetUsers,
                    request_deserializer=proto_dot_sso_dot_user__pb2.BatchGetUsersRequest.FromString,
                    response_serializer=proto_dot_sso_dot_user__pb2.BatchGetUsersResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=proto_dot_sso_dot_user__pb2.CreateUserRequest.FromString,
                    response_serializer=proto_dot_sso_dot_user__pb2.CreateUserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=proto_dot_sso_dot_user__pb2.UpdateUserRequest.FromString,
                    response_serializer=proto_dot_sso_dot_user__pb2.UpdateUserResponse.SerializeToString,
            ),
            'RemoveUserFromApps': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveUserFromApps,
                    request_deserializer=proto_dot_sso_dot_user__pb2.RemoveUserFromAppsRequest.FromString,
                    response_serializer=proto_dot_sso_dot_user__pb2.RemoveUserFromAppsResponse.SerializeToString,
            ),
            'AssignUserToApps': grpc.unary_unary_rpc_method_handler(
                    servicer.AssignUserToApps,
                    request_deserializer=proto_dot_sso_dot_user__pb2.AssignUserToAppsRequest.FromString,
                    response_serializer=proto_dot_sso_dot_user__pb2.AssignUserToAppsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sso.UserService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sso.UserService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UserService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sso.UserService/GetUser',
            proto_dot_sso_dot_user__pb2.GetUserRequest.SerializeToString,
            proto_dot_sso_dot_user__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserByEmail(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sso.UserService/GetUserByEmail',
            proto_dot_sso_dot_user__pb2.GetUserByEmailRequest.SerializeToString,
            proto_dot_sso_dot_user__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserByPhone(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sso.UserService/GetUserByPhone',
            proto_dot_sso_dot_user__pb2.GetUserByPhoneRequest.SerializeToString,
            proto_dot_sso_dot_user__pb2.UserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchGetUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sso.UserService/BatchGetUsers',
            proto_dot_sso_dot_user__pb2.BatchGetUsersRequest.SerializeToString,
            proto_dot_sso_dot_user__pb2.BatchGetUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sso.UserService/CreateUser',
            proto_dot_sso_dot_user__pb2.CreateUserRequest.SerializeToString,
            proto_dot_sso_dot_user__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sso.UserService/UpdateUser',
            proto_dot_sso_dot_user__pb2.UpdateUserRequest.SerializeToString,
            proto_dot_sso_dot_user__pb2.UpdateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveUserFromApps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sso.UserService/RemoveUserFromApps',
            proto_dot_sso_dot_user__pb2.RemoveUserFromAppsRequest.SerializeToString,
            proto_dot_sso_dot_user__pb2.RemoveUserFromAppsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AssignUserToApps(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sso.UserService/AssignUserToApps',
            proto_dot_sso_dot_user__pb2.AssignUserToAppsRequest.SerializeToString,
            proto_dot_sso_dot_user__pb2.AssignUserToAppsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
