# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/sso/user.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'proto/sso/user.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14proto/sso/user.proto\x12\x03sso\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc8\x03\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x12\n\x05\x65mail\x18\x03 \x01(\tH\x00\x88\x01\x01\x12\x12\n\x05phone\x18\x04 \x01(\tH\x01\x88\x01\x01\x12\x18\n\x0b\x61vatar_path\x18\x05 \x01(\tH\x02\x88\x01\x01\x12\x0e\n\x06status\x18\x06 \x01(\t\x12\x0c\n\x04role\x18\x07 \x01(\t\x12.\n\ncreated_at\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12.\n\nupdated_at\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\x05\x61lias\x18\n \x01(\tH\x03\x88\x01\x01\x12\x13\n\x06gender\x18\x0b \x01(\tH\x04\x88\x01\x01\x12\x36\n\rdate_of_birth\x18\x0c \x01(\x0b\x32\x1a.google.protobuf.TimestampH\x05\x88\x01\x01\x12\x14\n\x07\x61\x64\x64ress\x18\r \x01(\tH\x06\x88\x01\x01\x12\x10\n\x03\x62io\x18\x0e \x01(\tH\x07\x88\x01\x01\x42\x08\n\x06_emailB\x08\n\x06_phoneB\x0e\n\x0c_avatar_pathB\x08\n\x06_aliasB\t\n\x07_genderB\x10\n\x0e_date_of_birthB\n\n\x08_addressB\x06\n\x04_bio\"!\n\x0eGetUserRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"&\n\x15GetUserByEmailRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\"&\n\x15GetUserByPhoneRequest\x12\r\n\x05phone\x18\x01 \x01(\t\"(\n\x14\x42\x61tchGetUsersRequest\x12\x10\n\x08user_ids\x18\x01 \x03(\t\"1\n\x15\x42\x61tchGetUsersResponse\x12\x18\n\x05users\x18\x01 \x03(\x0b\x32\t.sso.User\"D\n\x0cUserResponse\x12\r\n\x05\x66ound\x18\x01 \x01(\x08\x12\x1c\n\x04user\x18\x02 \x01(\x0b\x32\t.sso.UserH\x00\x88\x01\x01\x42\x07\n\x05_user2\x8a\x02\n\x0bUserService\x12\x31\n\x07GetUser\x12\x13.sso.GetUserRequest\x1a\x11.sso.UserResponse\x12?\n\x0eGetUserByEmail\x12\x1a.sso.GetUserByEmailRequest\x1a\x11.sso.UserResponse\x12?\n\x0eGetUserByPhone\x12\x1a.sso.GetUserByPhoneRequest\x1a\x11.sso.UserResponse\x12\x46\n\rBatchGetUsers\x12\x19.sso.BatchGetUsersRequest\x1a\x1a.sso.BatchGetUsersResponseB6Z4github.com/ahmdfdhilah/arga-sso-service-v2/proto/ssob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.sso.user_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z4github.com/ahmdfdhilah/arga-sso-service-v2/proto/sso'
  _globals['_USER']._serialized_start=63
  _globals['_USER']._serialized_end=519
  _globals['_GETUSERREQUEST']._serialized_start=521
  _globals['_GETUSERREQUEST']._serialized_end=554
  _globals['_GETUSERBYEMAILREQUEST']._serialized_start=556
  _globals['_GETUSERBYEMAILREQUEST']._serialized_end=594
  _globals['_GETUSERBYPHONEREQUEST']._serialized_start=596
  _globals['_GETUSERBYPHONEREQUEST']._serialized_end=634
  _globals['_BATCHGETUSERSREQUEST']._serialized_start=636
  _globals['_BATCHGETUSERSREQUEST']._serialized_end=676
  _globals['_BATCHGETUSERSRESPONSE']._serialized_start=678
  _globals['_BATCHGETUSERSRESPONSE']._serialized_end=727
  _globals['_USERRESPONSE']._serialized_start=729
  _globals['_USERRESPONSE']._serialized_end=797
  _globals['_USERSERVICE']._serialized_start=800
  _globals['_USERSERVICE']._serialized_end=1066
# @@protoc_insertion_point(module_scope)
